stages:
  - test
  - build
  - deploy

.test:
  image: node:latest
  stage: test
  before_script:
    - cd $PROJECT_PATH
    - yarn install
  script:
    - yarn lint
    - yarn test

.docker:
  image: docker/compose:latest
  services:
    - docker:dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY

# test api:
#   extends: .test
#   variables: { PROJECT_PATH: api }

# test ui:
#   extends: .test
#   variables: { PROJECT_PATH: ui }

# build:
#   extends: .docker
#   stage: build
#   script:
#     - docker-compose build
#     - docker-compose push

deploy:
  extends: .docker
  stage: deploy
  variables:
    BACKEND_API_BASE_URL: http://ciascode.ascuy.me:3666
  script:
    - env
    - echo 'SOMETHING'
    - cat .env
    - docker-compose down
    - docker-compose up -d
