.test:
  image: node:latest
  before_script:
    - cd api
    - yarn install
  script:
    - yarn lint
    - yarn test

test api:
  extends: .test
  variables: { PROJECT_PATH: api }

test ui:
  extends: .test
  variables: { PROJECT_PATH: ui }
