test api:
  image: node:latest
  before_script:
    - cd api
    - yarn install
  script:
    - yarn lint
    - yarn test

test ui:
  image: node:latest
  before_script:
    - cd ui
    - yarn install
  script:
    - yarn lint
    - yarn test
