env:
  browser: true
  es6: true
  jest/globals: true
extends:
  - 'plugin:react/recommended'
  - airbnb
  - 'plugin:jest/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - jest
rules:
  quotes: [2, single]
  semi: [2, never]
  import/prefer-default-export: off
  object-curly-newline: off
  react/jsx-filename-extension: [ 1, { extensions: [.js, .jsx] } ]
  react/prop-types: off
  import/no-unresolved: off
  no-console: off
  prefer-object-spread: off
  jest/expect-expect: off
