env:
  browser: true
  es6: true
  jest/globals: true
extends:
  - airbnb-base
plugins:
  - jest
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  quotes: [2, single]
  semi: [2, never]
  import/prefer-default-export: off